version: '3.8'
services:
  web:
    build: ./client
    ports:
      - 3000:3000
  api: 
    build: ./server
    ports:
      - 8080:8080
    environment:
        - NAME=DOCKER_RUNING    
#   db:
#     image: mongo:4.0
#     ports: 
#       - 27017:27017
#     volumes:
#       - vidly:/data/db
# volumes:
#   vidly: 